include /etc/nginx/conf.d/upstream.inc;

server {
    listen 80; #80번 포트로 인입되는 클라이언트 기본 접속을 수신합니다.

    location / {
        proxy_pass http://backend; #backend 업스트림 그룹으로 트래핍 프록시 포워딩

        proxy_set_header Host $host;
    }
}